[CMAKE] GNUInstall Dir enhancements
ROCm/half pull request #6
Opened 2022-06-06 23:08 UTC by arvindcheru

Summary of proposed changes:
- Updated GNU install dir enhancements

2022-06-13 17:01 UTC, pfultz2 approved these changes

2022-06-17 16:11 UTC, lawruble13 requested changes

2022-06-17 16:11 UTC, lawruble13 commented on CMakeLists.txt
> +  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/include/half.hpp DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
As `OUTPUT_LOCATIONS` is unspecified in the call to `rocm_wrap_header_file`, it uses the value of `WRAPPER_LOCATIONS`, so the wrapper file will be output to `${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_INSTALL_INCLUDEDIR}/half.hpp`.
```suggestion
  install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_INSTALL_INCLUDEDIR}/half.hpp DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
```
The other option is to add `OUTPUT_LOCATIONS include` to the `rocm_wrap_header_file` call on line 31.

2022-06-20 19:30 UTC, lawruble13 approved these changes

2022-06-20 19:32 UTC, merged